### ISSUE TITLE
Redeliver

### ISSUE THREAD

**Issue by bkeepers** [probot/webhooks#5]
I know this is already on your list, but a button to redeliver a specific payload would be ✨

**Comment by JasonEtco** [comment]
Totally. The problem though is that since `webhooks` is, for all intents and purposes, a separate app, it can only redeliver to itself (which isn't very useful). As far as I know, the root `probot.receive()` that sends to all `robot`s isn't exposed anywhere, and we don't *yet* have a way to communicate between robots.

**Comment by JasonEtco** [comment]
I suppose it could POST the payload to its own `WEBHOOK_PATH` endpoint, but that could get messy with all the headers and things it expects...

**Comment by JasonEtco** [comment]
This works 🎉
